name: galaxy_lite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Sixtyfour
      fonts:
        - asset: fonts/Sixtyfour-Regular.ttf
        
    - family: Workbench
      fonts:
        - asset: fonts/Workbench-Regular.ttf
        

      
